"use client";

import { useState } from "react";
import { usePipelineStore } from "@/store/pipeline-store";
import { useVideoGeneration } from "@/lib/hooks/useVideoGeneration";

// Section headings we look for in the raw script
const SECTION_PATTERNS = [
  { key: "characters", regex: /^1\)\s/m, label: "Characters", icon: "👤" },
  { key: "no_characters", regex: /^2\)\s/m, label: "Scene (No Characters)", icon: "🏞️" },
  { key: "environment", regex: /^3\)\s/m, label: "Environment & Lighting", icon: "💡" },
  { key: "camera", regex: /^4\)\s/m, label: "Camera & Angle", icon: "🎥" },
  { key: "visual_style", regex: /^5\)\s/m, label: "Visual Style", icon: "🎨" },
  { key: "no_text", regex: /^6\)\s/m, label: "No Text / Graphics", icon: "🚫" },
  { key: "dialogue", regex: /^7\)\s/m, label: "Dialogue & Timing", icon: "🗣️" },
  { key: "action_breakdown", regex: /^8\)\s/m, label: "Action & Shot Breakdown", icon: "🎬" },
  { key: "output_quality", regex: /^9\)\s/m, label: "Output Quality", icon: "📐" },
];

function parseSections(rawScript: string) {
  const sections: { key: string; label: string; icon: string; content: string }[] = [];

  // Find all section positions
  const positions: { key: string; label: string; icon: string; start: number }[] = [];
  for (const pattern of SECTION_PATTERNS) {
    const match = rawScript.match(pattern.regex);
    if (match && match.index !== undefined) {
      positions.push({
        key: pattern.key,
        label: pattern.label,
        icon: pattern.icon,
        start: match.index,
      });
    }
  }

  // Sort by position
  positions.sort((a, b) => a.start - b.start);

  // Extract content between sections
  for (let i = 0; i < positions.length; i++) {
    const current = positions[i];
    const next = positions[i + 1];
    const content = next
      ? rawScript.slice(current.start, next.start).trim()
      : rawScript.slice(current.start).trim();

    // Remove the section number prefix (e.g., "1) " or "8) ")
    const cleaned = content.replace(/^\d+\)\s*/, "").trim();
    if (cleaned) {
      sections.push({
        key: current.key,
        label: current.label,
        icon: current.icon,
        content: cleaned,
      });
    }
  }

  // If no sections parsed, return the entire script as one block
  if (sections.length === 0) {
    return [{ key: "full", label: "Video Script", icon: "📝", content: rawScript }];
  }

  return sections;
}

export function ScriptResult() {
  const { script, currentStage } = usePipelineStore();
  const { startGeneration, isLoading } = useVideoGeneration();
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(["action_breakdown", "characters", "no_characters", "full"])
  );
  const [copied, setCopied] = useState(false);

  if (!script) return null;

  const sections = parseSections(script.rawScript);

  const toggleSection = (key: string) => {
    setExpandedSections((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const expandAll = () => {
    setExpandedSections(new Set(sections.map((s) => s.key)));
  };

  const collapseAll = () => {
    setExpandedSections(new Set());
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(script.rawScript);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
    }
  };

  return (
    <div className="animate-fade-in space-y-6">
      {/* Script Header */}
      <div className="bg-card border border-border rounded-xl p-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <h3 className="text-xl font-semibold">Video Clone Script</h3>
            <p className="text-sm text-muted mt-1">
              {sections.length} sections &middot; Generated by Gemini 2.5 Pro
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={expandAll}
              className="text-xs px-2.5 py-1 rounded-lg bg-background border border-border/50 text-muted hover:text-foreground transition-colors"
            >
              Expand All
            </button>
            <button
              onClick={collapseAll}
              className="text-xs px-2.5 py-1 rounded-lg bg-background border border-border/50 text-muted hover:text-foreground transition-colors"
            >
              Collapse All
            </button>
            <button
              onClick={handleCopy}
              className="text-xs px-2.5 py-1 rounded-lg bg-accent/10 text-accent hover:bg-accent/20 transition-colors"
            >
              {copied ? "Copied!" : "Copy Script"}
            </button>
          </div>
        </div>

        {/* Source URL */}
        <div className="p-3 bg-background rounded-lg border border-border/50">
          <p className="text-xs text-muted uppercase tracking-wider mb-1">Source Video</p>
          <p className="text-sm text-foreground/80 break-all">{script.videoUrl}</p>
        </div>
      </div>

      {/* Script Sections */}
      <div className="space-y-3">
        {sections.map((section) => {
          const isExpanded = expandedSections.has(section.key);
          const isActionBreakdown = section.key === "action_breakdown";

          return (
            <div
              key={section.key}
              className={`bg-card border rounded-xl overflow-hidden transition-colors ${
                isActionBreakdown
                  ? "border-accent/30"
                  : "border-border"
              }`}
            >
              {/* Section header — clickable to toggle */}
              <button
                onClick={() => toggleSection(section.key)}
                className="w-full flex items-center justify-between p-4 hover:bg-background/50 transition-colors text-left"
              >
                <div className="flex items-center gap-3">
                  <span className="text-lg">{section.icon}</span>
                  <span className="font-medium text-sm">{section.label}</span>
                  {isActionBreakdown && (
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-accent/10 text-accent font-medium">
                      KEY SECTION
                    </span>
                  )}
                </div>
                <svg
                  className={`w-4 h-4 text-muted transition-transform ${
                    isExpanded ? "rotate-180" : ""
                  }`}
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </button>

              {/* Section content */}
              {isExpanded && (
                <div className="px-4 pb-4 border-t border-border/30">
                  <pre className="text-sm text-foreground/80 leading-relaxed whitespace-pre-wrap font-sans mt-3">
                    {section.content}
                  </pre>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Generate Video Button */}
      {currentStage === "script_ready" && (
        <button
          onClick={() => startGeneration()}
          disabled={isLoading}
          className="w-full py-3.5 bg-accent hover:bg-accent-hover text-white font-medium rounded-xl transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
        >
          {isLoading ? (
            <>
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Starting Video Generation...
            </>
          ) : (
            <>
              <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"
                />
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              Generate Cloned Video with Sora / SeeDance
            </>
          )}
        </button>
      )}
    </div>
  );
}
